---
- name: "Disable the No-Subscription-Warning"
  include_tasks:
    file: "disable-no-subscription-warning.yml"
  when: "disable_no_subscription_warning"

- name: "Flatten the Snapshot Tree"
  include_tasks:
    file: "flatten-snapshot-tree.yml"
  when: "flatten_snapshot_tree"

- name: "Add CPU Temperature to Summary"
  include_tasks:
    file: "add-cpu-temperature-to-summary.yml"
  when: "add_cpu_temperature_to_summary"
